name: bioinformatics-portfolio
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - jupyterlab
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - xgboost
  - joblib
  - openpyxl
  - gdown
  - pytorch
  - torchvision
  - scanpy
  - harmonypy
  - python-igraph
  - leidenalg
  - anndata
  - catboost
  - scikit-survival
  - h5py
  - umap-learn
  - mofapy2
  - pip
  - pip:
      - timm
      - torchcam
      - captum
      - kagglehub
      - mofax
      - datasets
